export type ExpiringContractRow = {
  id: string;
  name: string;
  pos: string;
  teamAbbr: string;
  contractType: string;
  interestPct: number;
  age: number;
  estValue: number;
  currentSalary: number;
  maxValue: number;
};

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

const PHI_EXPIRING_CONTRACTS: ExpiringContractRow[] = [
  {
    id: slugify('Brandon Graham EDGE'),
    name: 'Brandon Graham',
    pos: 'EDGE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 34,
    estValue: 22299000,
    currentSalary: 0,
    maxValue: 26595000,
  },
  {
    id: slugify("Adoree' Jackson CB"),
    name: "Adoree' Jackson",
    pos: 'CB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 28,
    estValue: 17468000,
    currentSalary: 0,
    maxValue: 20850000,
  },
  {
    id: slugify('Dallas Goedert TE'),
    name: 'Dallas Goedert',
    pos: 'TE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 29,
    estValue: 13498000,
    currentSalary: 0,
    maxValue: 15881000,
  },
  {
    id: slugify('Ogbo Okoronkwo EDGE'),
    name: 'Ogbo Okoronkwo',
    pos: 'EDGE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 28,
    estValue: 22299000,
    currentSalary: 0,
    maxValue: 26595000,
  },
  {
    id: slugify('Matt Pryor OG'),
    name: 'Matt Pryor',
    pos: 'OG',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 29,
    estValue: 24631000,
    currentSalary: 0,
    maxValue: 27188000,
  },
  {
    id: slugify('Fred Johnson OT'),
    name: 'Fred Johnson',
    pos: 'OT',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 27,
    estValue: 24631000,
    currentSalary: 0,
    maxValue: 27188000,
  },
  {
    id: slugify('Marcus Epps S'),
    name: 'Marcus Epps',
    pos: 'S',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 29,
    estValue: 16043000,
    currentSalary: 0,
    maxValue: 20326000,
  },
  {
    id: slugify('Brett Toth OG'),
    name: 'Brett Toth',
    pos: 'OG',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 28,
    estValue: 24631000,
    currentSalary: 0,
    maxValue: 27188000,
  },
  {
    id: slugify('A.J. Dillon RB'),
    name: 'A.J. Dillon',
    pos: 'RB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 25,
    estValue: 11401000,
    currentSalary: 0,
    maxValue: 14143000,
  },
  {
    id: slugify('Joshua Uche EDGE'),
    name: 'Joshua Uche',
    pos: 'EDGE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 26,
    estValue: 22299000,
    currentSalary: 0,
    maxValue: 26595000,
  },
  {
    id: slugify('Quez Watkins WR'),
    name: 'Quez Watkins',
    pos: 'WR',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 24361000,
    currentSalary: 0,
    maxValue: 28046000,
  },
  {
    id: slugify('Braden Mann P'),
    name: 'Braden Mann',
    pos: 'P',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 27,
    estValue: 6075000,
    currentSalary: 0,
    maxValue: 6719000,
  },
  {
    id: slugify('Jaelan Phillips EDGE'),
    name: 'Jaelan Phillips',
    pos: 'EDGE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 25,
    estValue: 22299000,
    currentSalary: 0,
    maxValue: 26595000,
  },
  {
    id: slugify('Ambry Thomas CB'),
    name: 'Ambry Thomas',
    pos: 'CB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 17468000,
    currentSalary: 0,
    maxValue: 20850000,
  },
  {
    id: slugify('Kylen Granson TE'),
    name: 'Kylen Granson',
    pos: 'TE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 25,
    estValue: 13498000,
    currentSalary: 0,
    maxValue: 15881000,
  },
  {
    id: slugify('Azeez Ojulari EDGE'),
    name: 'Azeez Ojulari',
    pos: 'EDGE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 22299000,
    currentSalary: 0,
    maxValue: 26595000,
  },
  {
    id: slugify('Jahan Dotson WR'),
    name: 'Jahan Dotson',
    pos: 'WR',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 24361000,
    currentSalary: 0,
    maxValue: 28046000,
  },
  {
    id: slugify('Sam Howell QB'),
    name: 'Sam Howell',
    pos: 'QB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 39720000,
    currentSalary: 0,
    maxValue: 46073000,
  },
  {
    id: slugify('Nakobe Dean LB'),
    name: 'Nakobe Dean',
    pos: 'LB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 22,
    estValue: 22990000,
    currentSalary: 0,
    maxValue: 27454000,
  },
  {
    id: slugify('Grant Calcaterra TE'),
    name: 'Grant Calcaterra',
    pos: 'TE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 13498000,
    currentSalary: 0,
    maxValue: 15881000,
  },
  {
    id: slugify('Chance Campbell LB'),
    name: 'Chance Campbell',
    pos: 'LB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 22990000,
    currentSalary: 0,
    maxValue: 27454000,
  },
  {
    id: slugify('Tariq Castro-Fields CB'),
    name: 'Tariq Castro-Fields',
    pos: 'CB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 17468000,
    currentSalary: 0,
    maxValue: 20850000,
  },
  {
    id: slugify('Danny Gray WR'),
    name: 'Danny Gray',
    pos: 'WR',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 24361000,
    currentSalary: 0,
    maxValue: 28046000,
  },
  {
    id: slugify('Reed Blankenship S'),
    name: 'Reed Blankenship',
    pos: 'S',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 16043000,
    currentSalary: 0,
    maxValue: 20326000,
  },
  {
    id: slugify('Cameron Latu TE'),
    name: 'Cameron Latu',
    pos: 'TE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 13498000,
    currentSalary: 0,
    maxValue: 15881000,
  },
  {
    id: slugify('John Ojukwu OT'),
    name: 'John Ojukwu',
    pos: 'OT',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 25,
    estValue: 24631000,
    currentSalary: 0,
    maxValue: 27188000,
  },
  {
    id: slugify('Jose Ramirez EDGE'),
    name: 'Jose Ramirez',
    pos: 'EDGE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 22299000,
    currentSalary: 0,
    maxValue: 26595000,
  },
  {
    id: slugify('Ben VanSumeren LB'),
    name: 'Ben VanSumeren',
    pos: 'LB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 22990000,
    currentSalary: 0,
    maxValue: 27454000,
  },
  {
    id: slugify('E.J. Jenkins TE'),
    name: 'E.J. Jenkins',
    pos: 'TE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 24,
    estValue: 13498000,
    currentSalary: 0,
    maxValue: 15881000,
  },
  {
    id: slugify('Carson Steele RB'),
    name: 'Carson Steele',
    pos: 'RB',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 11401000,
    currentSalary: 0,
    maxValue: 14143000,
  },
  {
    id: slugify('Jaheim Bell TE'),
    name: 'Jaheim Bell',
    pos: 'TE',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 13498000,
    currentSalary: 0,
    maxValue: 15881000,
  },
  {
    id: slugify("Andre' Sam S"),
    name: "Andre' Sam",
    pos: 'S',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 16043000,
    currentSalary: 0,
    maxValue: 20326000,
  },
  {
    id: slugify('Gabe Hall DT'),
    name: 'Gabe Hall',
    pos: 'DT',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 21008000,
    currentSalary: 0,
    maxValue: 25602000,
  },
  {
    id: slugify('Darius Cooper WR'),
    name: 'Darius Cooper',
    pos: 'WR',
    teamAbbr: 'PHI',
    contractType: 'UFA',
    interestPct: 0,
    age: 23,
    estValue: 24361000,
    currentSalary: 0,
    maxValue: 28046000,
  },
];

const KC_EXPIRING_CONTRACTS: ExpiringContractRow[] = [
  {
    id: slugify('Travis Kelce TE'),
    name: 'Travis Kelce',
    pos: 'TE',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 81.0,
    age: 37,
    estValue: 17_125_000,
    currentSalary: 17_000_000,
    maxValue: 20_550_000,
  },
  {
    id: slugify('Marquise Brown WR'),
    name: 'Marquise Brown',
    pos: 'WR',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 49.5,
    age: 29,
    estValue: 7_000_000,
    currentSalary: 6_500_000,
    maxValue: 8_400_000,
  },
  {
    id: slugify('Charles Omenihu EDGE'),
    name: 'Charles Omenihu',
    pos: 'EDGE',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 54.3,
    age: 29,
    estValue: 4_000_000,
    currentSalary: 3_450_000,
    maxValue: 4_800_000,
  },
  {
    id: slugify('Jack Cochrane LB'),
    name: 'Jack Cochrane',
    pos: 'LB',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 8.6,
    age: 27,
    estValue: 2_100_000,
    currentSalary: 1_200_000,
    maxValue: 2_520_000,
  },
  {
    id: slugify('Nazeeh Johnson S'),
    name: 'Nazeeh Johnson',
    pos: 'S',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 2.0,
    age: 28,
    estValue: 1_900_000,
    currentSalary: 1_200_000,
    maxValue: 2_280_000,
  },
  {
    id: slugify('Jerry Tillery IDL'),
    name: 'Jerry Tillery',
    pos: 'IDL',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 36.2,
    age: 30,
    estValue: 1_790_000,
    currentSalary: 1_790_000,
    maxValue: 2_148_000,
  },
  {
    id: slugify('James Winchester LS'),
    name: 'James Winchester',
    pos: 'LS',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 30.6,
    age: 37,
    estValue: 1_650_000,
    currentSalary: 1_650_000,
    maxValue: 1_980_000,
  },
  {
    id: slugify('Kareem Hunt RB'),
    name: 'Kareem Hunt',
    pos: 'RB',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 47.5,
    age: 31,
    estValue: 1_500_000,
    currentSalary: 850_000,
    maxValue: 1_800_000,
  },
  {
    id: slugify('Bryan Cook S'),
    name: 'Bryan Cook',
    pos: 'S',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 82.4,
    age: 27,
    estValue: 1_461_786,
    currentSalary: 3_108_247,
    maxValue: 1_754_143,
  },
  {
    id: slugify('Derrick Nnadi IDL'),
    name: 'Derrick Nnadi',
    pos: 'IDL',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 29.6,
    age: 30,
    estValue: 1_422_500,
    currentSalary: 417_500,
    maxValue: 1_707_000,
  },
  {
    id: slugify('JuJu Smith-Schuster WR'),
    name: 'JuJu Smith-Schuster',
    pos: 'WR',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 55.7,
    age: 30,
    estValue: 1_422_500,
    currentSalary: 1_197_500,
    maxValue: 1_707_000,
  },
  {
    id: slugify('Leo Chenal LB'),
    name: 'Leo Chenal',
    pos: 'LB',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 42.3,
    age: 26,
    estValue: 1_261_226,
    currentSalary: 849_020,
    maxValue: 1_513_471,
  },
  {
    id: slugify('Robert Tonyan TE'),
    name: 'Robert Tonyan',
    pos: 'TE',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 11.9,
    age: 32,
    estValue: 1_255_000,
    currentSalary: 0,
    maxValue: 1_506_000,
  },
  {
    id: slugify('Mike Pennel IDL'),
    name: 'Mike Pennel',
    pos: 'IDL',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 29.0,
    age: 35,
    estValue: 1_255_000,
    currentSalary: 0,
    maxValue: 1_506_000,
  },
  {
    id: slugify('Deon Bush S'),
    name: 'Deon Bush',
    pos: 'S',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 0.0,
    age: 33,
    estValue: 1_255_000,
    currentSalary: 0,
    maxValue: 1_506_000,
  },
  {
    id: slugify('Mike Edwards S'),
    name: 'Mike Edwards',
    pos: 'S',
    teamAbbr: 'KC',
    contractType: 'UFA',
    interestPct: 11.4,
    age: 30,
    estValue: 1_170_000,
    currentSalary: 0,
    maxValue: 1_404_000,
  },
];

export const getExpiringContractsByTeam = (teamAbbr?: string): ExpiringContractRow[] => {
  const normalized = teamAbbr?.toUpperCase();
  if (normalized === 'KC') {
    return KC_EXPIRING_CONTRACTS;
  }
  if (normalized === 'PHI') {
    return PHI_EXPIRING_CONTRACTS;
  }
  return [];
};

export const EXPIRING_CONTRACTS: ExpiringContractRow[] = [
  ...PHI_EXPIRING_CONTRACTS,
  ...KC_EXPIRING_CONTRACTS,
];
