export const REWARD_ACTION_YARDS = {
  TRIVIA_CORRECT: 1,
  TRIVIA_GAME_COMPLETE: 2,
  TRIVIA_BUDDY_WIN: 3,
  DAILY_TRIVIA_CORRECT: 1,
  CATCH_UP_COMPLETE: 1,
  PREDICTION_SUBMITTED: 1,
  PREDICTION_CORRECT: 2,
  GAME_DAY_CHECKIN: 2,
} as const;

export type RewardActionType = keyof typeof REWARD_ACTION_YARDS;

export const REWARD_DEFINITIONS = [
  {
    id: 'yards-50',
    thresholdYards: 50,
    type: 'DISCOUNT',
    title: '5% off merch',
    description: 'One-time discount on a merch order.',
    discountPercent: 5,
    usageLimit: 1,
  },
  {
    id: 'yards-100',
    thresholdYards: 100,
    type: 'DISCOUNT',
    title: '10% off merch',
    description: 'One-time discount on a merch order.',
    discountPercent: 10,
    usageLimit: 1,
  },
  {
    id: 'yards-250',
    thresholdYards: 250,
    type: 'DISCOUNT',
    title: '15% off merch',
    description: 'One-time discount on a merch order.',
    discountPercent: 15,
    usageLimit: 1,
  },
  {
    id: 'yards-500',
    thresholdYards: 500,
    type: 'DISCOUNT',
    title: '20% off merch',
    description: 'One-time discount on a merch order.',
    discountPercent: 20,
    usageLimit: 1,
  },
  {
    id: 'yards-1000',
    thresholdYards: 1000,
    type: 'DISCOUNT',
    title: '25% off merch',
    description: 'One-time discount on a merch order.',
    discountPercent: 25,
    usageLimit: 1,
  },
  {
    id: 'yards-2500',
    thresholdYards: 2500,
    type: 'DISCOUNT',
    title: '30% off merch',
    description: 'One-time discount on a merch order.',
    discountPercent: 30,
    usageLimit: 1,
  },
  {
    id: 'yards-5000',
    thresholdYards: 5000,
    type: 'STICKER_PACK',
    title: 'Free D&D sticker pack',
    description: 'Claim a free Down & Distance sticker pack.',
    discountPercent: null,
    usageLimit: 1,
  },
  {
    id: 'yards-10000',
    thresholdYards: 10000,
    type: 'DISCOUNT',
    title: '40% off one merch order',
    description: 'Premium, one-time, non-stackable discount.',
    discountPercent: 40,
    usageLimit: 1,
  },
] as const;
