import type { OwnershipIconName } from '@/components/ui/ownership-icon';

// Names resolve to the supplied manifest; no generic wrench for unrelated investments.
export const ownershipProjectIcons = {
  wifi: 'wi-fi',
  suites: 'suites',
  concessions: 'concessions',
  restrooms: 'restrooms',
  boards: 'video-boards',
  club: 'club-seating',
  gates: 'entry-gates',
  sound: 'sound',
  markets: 'grab-and-go',
  access: 'accessibility',
  renovate: 'renovate',
  expand: 'expand',
  'new-stadium': 'new-stadium',
  training: 'training-facility',
  weights: 'dumbbell',
  medical: 'medical-center',
  recovery: 'recovery',
  nutrition: 'nutrition',
  amenities: 'player-amenities',
  fields: 'practice-fields',
  scouting: 'scouting',
  technology: 'facility-technology',
  offices: 'team-offices',
  transit: 'parking',
  community: 'community-investment',
  digital: 'digital-social',
  merch: 'merchandise',
} as const satisfies Record<string, OwnershipIconName>;
export const ownershipSectionIcons = {
  central: 'owners-desk',
  stadium: 'stadium',
  facilities: 'training-facility',
  business: 'annual-revenue',
  fans: 'fans',
  'report-card': 'report-card',
  legacy: 'legacy',
} as const satisfies Record<string, OwnershipIconName>;
export const ownershipLabelIcons: Record<string, OwnershipIconName> = {
  'Franchise Value': 'franchise-value',
  'Annual Revenue': 'annual-revenue',
  'Operating Income': 'operating-income',
  'Available Capital': 'available-capital',
  Stadium: 'stadium',
  'Your Stadium': 'stadium',
  'Stadium Snapshot': 'stadium',
  'Stadium Rating': 'stadium',
  'Player Report Card': 'report-card',
  'Owner’s Desk': 'owners-desk',
  Facilities: 'training-facility',
  'Fan & Market': 'market',
  'Business & Partnerships': 'partnerships',
  'Recent Ownership Activity': 'milestones',
  'Development resources': 'player-development',
  'Health & recovery': 'recovery',
  'Health & recovery resources': 'medical-center',
  'Player amenities / appeal': 'player-amenities',
  'Free-agent appeal': 'free-agent-appeal',
  'Overall facilities': 'training-facility',
  'Fan Approval': 'fan-experience',
  'Season Ticket Renewal': 'season-ticket-renewal',
  'Community Impact': 'community',
  'Stadium Experience': 'fan-experience',
  Tickets: 'ticket-revenue',
  Sponsorships: 'sponsorship',
  Merchandise: 'merchandise',
  'Naming Rights': 'naming-rights',
  Concessions: 'concessions',
  Other: 'budget',
  'Active Projects': 'shovel',
  'Overall Rating': 'report-card',
  'Completed Investments': 'investment',
  'Category Ratings': 'report-card',
  'Annual Revenue Breakdown': 'annual-revenue',
  'Current Partnerships': 'partnerships',
  'Fan Experience Rating': 'fan-experience',
  Attendance: 'attendance',
  'Fan Sentiment': 'fan-sentiment',
  'Key Fan Insights': 'fan-insights',
  'Featured Initiative': 'featured-initiative',
  'Fan Snapshot': 'fans',
  'What Fans Are Saying': 'fan-feedback',
  'Ticketing Policy': 'pricing',
  'Fan & Revenue Impact': 'market',
  'Projected Revenue': 'annual-revenue',
  Affordability: 'pricing',
  'Fan sentiment': 'fan-sentiment',
  'Game-day atmosphere': 'game-day',
  'Ticket affordability': 'pricing',
  'Concessions & food': 'concessions',
  'Parking & transportation': 'parking',
  'Community involvement': 'community',
  'Treatment of Families': 'families',
  'Food / Dining': 'food',
  Nutrition: 'nutrition',
  'Locker Room': 'locker-room',
  'Training Room': 'treatment-room',
  'Training Staff': 'training-staff',
  'Weight Room': 'dumbbell',
  Ownership: 'owners-desk',
  'Owner Tenure': 'owner-tenure',
  'Franchise Value Growth': 'trend',
  'Capital Invested': 'investment',
  'Current Record': 'win-loss-history',
  'Franchise Milestones': 'milestones',
  'Season & Fan Approval History': 'loyalty',
  'Ownership Timeline': 'legacy',
  Championships: 'championships',
  'Playoff appearances': 'playoff-appearances',
  'Completed stadium projects': 'stadium',
  'Facility investment': 'investment',
  'Community investment': 'community-investment',
  'Business agreements': 'contract',
  'Current fan approval': 'fan-experience',
  'Fan Experience': 'fan-experience',
  Ticketing: 'ticket-revenue',
  Community: 'community',
  'Digital & Social': 'digital-social',
  'Game Day': 'game-day',
  'Fan Feedback': 'fan-feedback',
};
