// Bundled copies of the same NFL SVG assets used by TEAM_LIST on web.
export const teamLogoAssets: Record<string, number> = {
  ARI: require('../assets/team-logos/ARI.svg'),
  ATL: require('../assets/team-logos/ATL.svg'),
  BAL: require('../assets/team-logos/BAL.svg'),
  BUF: require('../assets/team-logos/BUF.svg'),
  CAR: require('../assets/team-logos/CAR.svg'),
  CHI: require('../assets/team-logos/CHI.svg'),
  CIN: require('../assets/team-logos/CIN.svg'),
  CLE: require('../assets/team-logos/CLE.svg'),
  DAL: require('../assets/team-logos/DAL.svg'),
  DEN: require('../assets/team-logos/DEN.svg'),
  DET: require('../assets/team-logos/DET.svg'),
  GB: require('../assets/team-logos/GB.svg'),
  HOU: require('../assets/team-logos/HOU.svg'),
  IND: require('../assets/team-logos/IND.svg'),
  JAX: require('../assets/team-logos/JAX.svg'),
  KC: require('../assets/team-logos/KC.svg'),
  LAC: require('../assets/team-logos/LAC.svg'),
  LAR: require('../assets/team-logos/LAR.svg'),
  LV: require('../assets/team-logos/LV.svg'),
  MIA: require('../assets/team-logos/MIA.svg'),
  MIN: require('../assets/team-logos/MIN.svg'),
  NE: require('../assets/team-logos/NE.svg'),
  NO: require('../assets/team-logos/NO.svg'),
  NYG: require('../assets/team-logos/NYG.svg'),
  NYJ: require('../assets/team-logos/NYJ.svg'),
  PHI: require('../assets/team-logos/PHI.svg'),
  PIT: require('../assets/team-logos/PIT.svg'),
  SEA: require('../assets/team-logos/SEA.svg'),
  SF: require('../assets/team-logos/SF.svg'),
  TB: require('../assets/team-logos/TB.svg'),
  TEN: require('../assets/team-logos/TEN.svg'),
  WAS: require('../assets/team-logos/WAS.svg'),
};
