export type FreeAgentProfileDTO = {
  source: 'real' | 'seed' | 'released';
  marketStatus: 'unsigned' | 'available' | 'signed' | 'removed';
  marketTier: 'elite' | 'starter' | 'depth' | 'fringe';
  roleTier: 'starter' | 'depth' | 'developmental';
  playerId: string;
  saveId: string;
  expectedYears: number;
  expectedAPY: number;
  expectedGuarantee: number;
  ageFactor: number;
  position: string;
  availabilityStatus: 'available' | 'signed' | 'removed';
  lastUpdated: string;
  expectedAnnualValue: number;
  expectedContractYears: number;
  guaranteeExpectationPct: number;
  guaranteedMoneyDemand: number;
  ageCurveFactor: number;
  declineRisk: number;
  demandScore: number;
  signingDifficulty: number;
  competitionScore: number;
  signingInterestScore: number;
  teamFitScore: number;
  bestFitTeamAbbr?: string;
  schemeFitTags: string[];
  available: boolean;
  generatedAt: string;
  refreshedAt: string;
};

export type PlayerRowDTO = {
  id: string;
  firstName: string;
  lastName: string;
  position: string;
  age?: number;
  marketValue?: number | null;
  rating?: number;
  rank?: number;
  projectedPick?: number;
  college?: string;
  grade?: string;
  projectedRound?: string;
  contractYearsRemaining: number;
  capHit: string;
  capHitValue?: number;
  salary?: number;
  guaranteed?: number;
  deadCap?: number;
  releaseSavings?: number;
  postJune1Savings?: number;
  disgruntled?: boolean;
  status: string;
  headshotUrl?: string | null;
  isDrafted?: boolean;
  signedTeamAbbr?: string | null;
  signedTeamLogoUrl?: string | null;
  signedAt?: string | null;
  cutAt?: string | null;
  freeAgentProfile?: FreeAgentProfileDTO;
  contract?: {
    yearsRemaining: number;
    apy: number;
    guaranteed: number;
    capHit: number;
    expiresAfterSeason: boolean;
  };
};
