import type { UnifiedPlayerStats } from '@/server/data/nfl-data';

export type FreeAgentProfileDTO = {
  source: 'real' | 'seed' | 'released';
  marketStatus: 'unsigned' | 'available' | 'signed' | 'removed';
  marketTier: 'elite' | 'starter' | 'depth' | 'fringe';
  roleTier: 'starter' | 'depth' | 'developmental';
  playerId: string;
  saveId: string;
  expectedYears: number;
  expectedAPY: number;
  expectedGuarantee: number;
  ageFactor: number;
  position: string;
  availabilityStatus: 'available' | 'signed' | 'removed';
  lastUpdated: string;
  expectedAnnualValue: number;
  expectedContractYears: number;
  guaranteeExpectationPct: number;
  guaranteedMoneyDemand: number;
  ageCurveFactor: number;
  declineRisk: number;
  demandScore: number;
  signingDifficulty: number;
  competitionScore: number;
  signingInterestScore: number;
  teamFitScore: number;
  bestFitTeamAbbr?: string;
  schemeFitTags: string[];
  available: boolean;
  generatedAt: string;
  refreshedAt: string;
};

export type PlayerRowDTO = {
  id: string;
  firstName: string;
  lastName: string;
  teamAbbr?: string | null;
  normalizedName?: string;
  position: string;
  school?: string | null;
  age?: number;
  height?: string | null;
  weight?: number | null;
  baselineRating?: number | null;
  maddenRating?: number | null;
  marketValue?: number | null;
  rating?: number;
  stats?: UnifiedPlayerStats;
  rank?: number;
  projectedPick?: number;
  college?: string;
  grade?: string;
  projectedRound?: string;
  espnPlayerId?: string | null;
  espnProfileUrl?: string | null;
  classYear?: string | null;
  hometown?: string | null;
  summary?: string | null;
  archetype?: string | null;
  projectedRange?: string | null;
  source?: string | null;
  contractYearsRemaining: number;
  capHit: string;
  capHitValue?: number;
  salary?: number;
  guaranteed?: number;
  deadCap?: number;
  releaseSavings?: number;
  postJune1Savings?: number;
  disgruntled?: boolean;
  status: string;
  headshotUrl?: string | null;
  isDrafted?: boolean;
  signedTeamAbbr?: string | null;
  signedTeamLogoUrl?: string | null;
  signedAt?: string | null;
  cutAt?: string | null;
  lastTeamAbbr?: string | null;
  currentTeamAbbr?: string | null;
  contractStatus?: string | null;
  isUnsigned?: boolean;
  averagePerYear?: number | null;
  expectedAnnualValue?: number | null;
  originalAskAnnualValue?: number | null;
  currentAskAnnualValue?: number | null;
  askReductionAmount?: number | null;
  askReductionPct?: number | null;
  signedWave?: 1 | 2 | 3 | null;
  isSignedByUser?: boolean;
  isSignedByCpu?: boolean;
  marketTier?: 'elite' | 'starter' | 'depth' | 'fringe';
  marketStatus?: 'unsigned' | 'available' | 'signed' | 'removed';
  availabilityStatus?: 'available' | 'signed' | 'removed';
  freeAgentProfile?: FreeAgentProfileDTO;
  contract?: {
    yearsRemaining: number;
    apy: number;
    guaranteed: number;
    capHit: number;
    expiresAfterSeason: boolean;
  };
};
