export type PlayerRowDTO = {
  id: string;
  firstName: string;
  lastName: string;
  position: string;
  age?: number;
  rating?: number;
  rank?: number;
  college?: string;
  grade?: string;
  projectedRound?: string;
  contractYearsRemaining: number;
  capHit: string;
  capHitValue?: number;
  salary?: number;
  guaranteed?: number;
  deadCap?: number;
  disgruntled?: boolean;
  status: string;
  headshotUrl?: string | null;
  isDrafted?: boolean;
  signedTeamAbbr?: string | null;
  signedTeamLogoUrl?: string | null;
  contract?: {
    yearsRemaining: number;
    apy: number;
    guaranteed: number;
    capHit: number;
    expiresAfterSeason: boolean;
  };
};
