import { authDb } from '@/server/auth/database';

type VerifiedVideoSource = readonly [string | null, string, string, string, string, string];

// Exact, approved channel matches exported from the resolver. Channel IDs are public,
// non-secret identifiers, so production can sync these without using search quota.
export const VERIFIED_VIDEO_SOURCES: readonly VerifiedVideoSource[] = [
  [
    'ARI',
    'YT_ARI_ARIZONA_CARDINALS',
    'Arizona Cardinals',
    'UCzNfiKcvNjLHljohEkO83Rg',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'ATL',
    'YT_ATL_ATLANTA_FALCONS',
    'Atlanta Falcons',
    'UCzjCfV3LHyarKbdb-2ScGZg',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'ATL',
    'YT_ATL_LOCKED_ON_FALCONS',
    'Locked On Falcons',
    'UCf0YzYctxDlpPgYXxTwn8hw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'BAL',
    'YT_BAL_BALTIMORE_RAVENS',
    'Baltimore Ravens',
    'UCbpj2JAUMb8G_oQQFPeGrhg',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'BAL',
    'YT_BAL_INGRAVENVIDS',
    'IngravenVids',
    'UCWKlx05vtSnpdSa6q47H9ng',
    'independent_media',
    'YOUTUBE',
  ],
  [
    'BAL',
    'YT_BAL_LOCKED_ON_RAVENS',
    'Locked On Ravens',
    'UCkUKvLTxP2wuyGs_ALuIaIg',
    'podcast',
    'YOUTUBE',
  ],
  [
    'BUF',
    'YT_BUF_BUFFALO_BILLS',
    'Buffalo Bills',
    'UCcEvCxUe2Sm5W6MliEUv0vg',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'BUF',
    'YT_BUF_BUFFALO_PLUS',
    'Buffalo Plus',
    'UCCS1NlZ4loA0HIAuvxLA8pQ',
    'independent_media',
    'YOUTUBE',
  ],
  ['BUF', 'YT_BUF_COVER_1', 'Cover 1', 'UClL6eJS1s8xmRoYRQbYgxQQ', 'independent_media', 'YOUTUBE'],
  [
    'BUF',
    'YT_BUF_LOCKED_ON_BILLS',
    'Locked On Bills',
    'UCB53sJjGaYU8RmLV9F9wPvQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'CAR',
    'YT_CAR_C3_PANTHERS_PODCAST',
    'C3 Panthers Podcast',
    'UCQwJvLJUDRwWoh9KlYqL-Lg',
    'independent_media',
    'YOUTUBE',
  ],
  [
    'CAR',
    'YT_CAR_CAROLINA_PANTHERS',
    'Carolina Panthers',
    'UC6vl4XAyO5mZLczhFC8MgpA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'CHI',
    'YT_CHI_CHICAGO_BEARS',
    'Chicago Bears',
    'UCP0Cdc6moLMyDJiO0s-yhbQ',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'CHI',
    'YT_CHI_LOCKED_ON_BEARS',
    'Locked On Bears',
    'UCXCnRo-iwMsS4iC1SobeGHA',
    'podcast',
    'YOUTUBE',
  ],
  [
    'CIN',
    'YT_CIN_CINCINNATI_BENGALS',
    'Cincinnati Bengals',
    'UCnQUpSnJ39KsjZKbT0CprHQ',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'CIN',
    'YT_CIN_LOCKED_ON_BENGALS',
    'Locked On Bengals',
    'UCc2xlqI7QW8QHvMJ8NR2Ltg',
    'podcast',
    'YOUTUBE',
  ],
  [
    'CLE',
    'YT_CLE_CLEVELAND_BROWNS',
    'Cleveland Browns',
    'UCQQQO7Kdo0cu9iEb19qOoYA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'CLE',
    'YT_CLE_LOCKED_ON_BROWNS',
    'Locked On Browns',
    'UC3iTW4tsgRrkU1sKw9AQNrg',
    'podcast',
    'YOUTUBE',
  ],
  [
    'DAL',
    'YT_DAL_DALLAS_COWBOYS',
    'Dallas Cowboys',
    'UCC0BPKJxAyxjQoRTYbpW0FQ',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'DAL',
    'YT_DAL_LOCKED_ON_COWBOYS',
    'Locked On Cowboys',
    'UCnAXfqh9nujPUFYW6r3gJEQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'DEN',
    'YT_DEN_DENVER_BRONCOS',
    'Denver Broncos',
    'UCDGdBexlDZA8T7hnweWWyow',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'DEN',
    'YT_DEN_LOCKED_ON_BRONCOS',
    'Locked On Broncos',
    'UC8KxsM2xSTTHKJOH6JDT7fw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'DET',
    'YT_DET_DETROIT_LIONS',
    'Detroit Lions',
    'UCv5J06V-ESk5_1uriG65f3w',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'DET',
    'YT_DET_LOCKED_ON_LIONS',
    'Locked On Lions',
    'UCV2XEkdzy4f0YQP6EjRbEsQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'GB',
    'YT_GB_LOCKED_ON_PACKERS',
    'Locked On Packers',
    'UCufUP6i_pdfTjqVEswITOmw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'HOU',
    'YT_HOU_HOUSTON_TEXANS',
    'Houston Texans',
    'UCa_FcpOBe8G6VAR18RYS-aA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'HOU',
    'YT_HOU_LOCKED_ON_TEXANS',
    'Locked On Texans',
    'UCiFQGjNHUQPVrg-aQL5FtgA',
    'podcast',
    'YOUTUBE',
  ],
  [
    'IND',
    'YT_IND_INDIANAPOLIS_COLTS',
    'Indianapolis Colts',
    'UCyYn26HPC4HIedifGnNbjBw',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'IND',
    'YT_IND_LOCKED_ON_COLTS',
    'Locked On Colts',
    'UCLdpxJspi1hMh5HL7ExpWOQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'JAX',
    'YT_JAX_JACKSONVILLE_JAGUARS',
    'Jacksonville Jaguars',
    'UCsGacW6z0GedR-Wv45SBRZg',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'JAX',
    'YT_JAX_LOCKED_ON_JAGUARS',
    'Locked On Jaguars',
    'UCFmdmMtDxkm4akuk83rWxuQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'KC',
    'YT_KC_ALL_CHIEF_D_UP',
    "All Chief'd Up",
    'UCkjfeqNG7vZb56Vo4DUMQfA',
    'independent_media',
    'YOUTUBE',
  ],
  [
    'KC',
    'YT_KC_ARROWHEAD_ADDICT_PODCAST',
    'Arrowhead Addict Podcast',
    'UC3CdquRsu60VZcbGMfr1WgQ',
    'independent_media',
    'YOUTUBE',
  ],
  ['KC', 'YT_KC_CHIEFSTV', 'ChiefsTV', 'UCm7aNg87CtuXIcqaVnajQcA', 'independent_media', 'YOUTUBE'],
  [
    'KC',
    'YT_KC_HOW_BOUT_THOSE_CHIEFS',
    'How Bout Those Chiefs',
    'UCXVTDRVpgxQ2dHW6-EzyJ3Q',
    'independent_media',
    'YOUTUBE',
  ],
  [
    'KC',
    'YT_KC_KANSAS_CITY_CHIEFS',
    'Kansas City Chiefs',
    'UC-hXefb6XBFSubWz6Ezf_lA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'KC',
    'YT_KC_LOCKED_ON_CHIEFS',
    'Locked On Chiefs',
    'UCYjOu3YQnL9F24XEFnaMrNg',
    'podcast',
    'YOUTUBE',
  ],
  ['KC', 'YT_KC_RGR_FOOTBALL', 'RGR Football', 'UC1quXkJYOUHlDSw-6tMe-Fg', 'film', 'YOUTUBE'],
  [
    'LAC',
    'YT_LAC_LOCKED_ON_CHARGERS',
    'Locked On Chargers',
    'UC3q-ntwngTE3tGfWVgHirFQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'LAC',
    'YT_LAC_LOS_ANGELES_CHARGERS',
    'Los Angeles Chargers',
    'UCUyz_gEY_N-KBU4zjt2s-uQ',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'LAR',
    'YT_LAR_LOCKED_ON_RAMS',
    'Locked On Rams',
    'UCUhG_loQ0D9YF2Gdn-IfUOw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'LAR',
    'YT_LAR_LOS_ANGELES_RAMS',
    'Los Angeles Rams',
    'UCyJ6yZdVUkBvt2vl4R03jcA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'LV',
    'YT_LV_LOCKED_ON_RAIDERS',
    'Locked On Raiders',
    'UCVgPs0As0pzp6zsYJLB7zNA',
    'podcast',
    'YOUTUBE',
  ],
  [
    'MIA',
    'YT_MIA_LOCKED_ON_DOLPHINS',
    'Locked On Dolphins',
    'UCVqSIFp40ZjJtX2iB6NoYsg',
    'podcast',
    'YOUTUBE',
  ],
  [
    'MIA',
    'YT_MIA_MIAMI_DOLPHINS',
    'Miami Dolphins',
    'UCHUSfEzpSRkUUsRkk_aJwDw',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'MIN',
    'YT_MIN_LOCKED_ON_VIKINGS',
    'Locked On Vikings',
    'UCU9qwCJcClgWI0JNTezBLqQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'MIN',
    'YT_MIN_MINNESOTA_VIKINGS',
    'Minnesota Vikings',
    'UCcsw_KrB_wg5lQ5nXWR_LFA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'NE',
    'YT_NE_LOCKED_ON_PATRIOTS',
    'Locked On Patriots',
    'UCcsHJ8Mz11n5uPl5_XE9o-w',
    'podcast',
    'YOUTUBE',
  ],
  [
    'NO',
    'YT_NO_LOCKED_ON_SAINTS',
    'Locked On Saints',
    'UCvovqdIpy0yua8lfYQqvOOQ',
    'podcast',
    'YOUTUBE',
  ],
  [
    'NO',
    'YT_NO_NEW_ORLEANS_SAINTS',
    'New Orleans Saints',
    'UCwuddf1JrodMlc5fYpVlrQA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'NYG',
    'YT_NYG_NEW_YORK_GIANTS',
    'New York Giants',
    'UCk2FqoG8dN5EAz5WU3A0D7A',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'NYJ',
    'YT_NYJ_NEW_YORK_JETS',
    'New York Jets',
    'UCROj9vBjc4ZW3AL4cd_BjHg',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'PHI',
    'YT_PHI_PHILADELPHIA_EAGLES',
    'Philadelphia Eagles',
    'UCaogx6OHpsGg0zuGRKsjbtQ',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'PIT',
    'YT_PIT_LOCKED_ON_STEELERS',
    'Locked On Steelers',
    'UC7JorgD8nGLtvvMy1ogFetg',
    'podcast',
    'YOUTUBE',
  ],
  [
    'PIT',
    'YT_PIT_PITTSBURGH_STEELERS',
    'Pittsburgh Steelers',
    'UChaRXjMDs4ppKfnTPE6Z89w',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'SEA',
    'YT_SEA_LOCKED_ON_SEAHAWKS',
    'Locked On Seahawks',
    'UCgmJDvoBn-0yMpw_DsPd56A',
    'podcast',
    'YOUTUBE',
  ],
  [
    'SEA',
    'YT_SEA_SEATTLE_SEAHAWKS',
    'Seattle Seahawks',
    'UCzkFCRiMcOBeef8xcaqipmw',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'SF',
    'YT_SF_LOCKED_ON_49ERS',
    'Locked On 49ers',
    'UCnGbIUIQqodxdMm_Jg93JjA',
    'podcast',
    'YOUTUBE',
  ],
  [
    'SF',
    'YT_SF_SAN_FRANCISCO_49ERS',
    'San Francisco 49ers',
    'UCeIOarQkwmGhimim9cDUTng',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'TB',
    'YT_TB_LOCKED_ON_BUCS',
    'Locked On Bucs',
    'UC3BqKbRUIwBNZ1WKFLw-0nw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'TB',
    'YT_TB_TAMPA_BAY_BUCCANEERS',
    'Tampa Bay Buccaneers',
    'UC0Wwu7r1ybaaR09ANhudTzA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'TEN',
    'YT_TEN_LOCKED_ON_TITANS',
    'Locked On Titans',
    'UCP3332GMOh4y5PX3q9NFybw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'TEN',
    'YT_TEN_TENNESSEE_TITANS',
    'Tennessee Titans',
    'UCHBsqVkFraWvtNd1w0Qx4_g',
    'official',
    'OFFICIAL_TEAM',
  ],
  [
    'WAS',
    'YT_WAS_LOCKED_ON_COMMANDERS',
    'Locked On Commanders',
    'UCd2DqmOXnb1gLKf13eg5uzw',
    'podcast',
    'YOUTUBE',
  ],
  [
    'WAS',
    'YT_WAS_WASHINGTON_COMMANDERS',
    'Washington Commanders',
    'UC2a0ENbCZqIO5C1fWXGXZXA',
    'official',
    'OFFICIAL_TEAM',
  ],
  [null, 'YT_NFL_MATTYDUBS', 'Mattydubs', 'UCJ-kd8U-odAVk4iwWO5fCFA', 'film', 'YOUTUBE'],
];

export async function syncVerifiedVideoSources(teamId?: string, force = false) {
  const sql = authDb();
  const sources = VERIFIED_VIDEO_SOURCES.filter(
    ([sourceTeamId]) => !teamId || sourceTeamId === teamId || sourceTeamId === null,
  );
  for (const [sourceTeamId, id, name, channelId, category, sourceType] of sources) {
    const official = category === 'official';
    await sql`
      INSERT INTO content_sources(
        id,name,source_type,team_id,league_wide,url,fetch_strategy,polling_tier,
        priority,reliability_score,check_interval_seconds,enabled,metadata,next_check_at
      ) VALUES(
        ${id},${name},${sourceType},${sourceTeamId},${sourceTeamId === null},
        ${`https://www.youtube.com/channel/${channelId}`},'STRUCTURED_API',
        ${official ? 'A' : 'B'},${official ? 100 : 85},${official ? 1 : 0.85},21600,true,
        ${sql.json({
          platform: 'YOUTUBE',
          youtubeChannelId: channelId,
          youtubeUploadsPlaylistId: `UU${channelId.slice(2)}`,
          category,
          scope: sourceTeamId ? 'team' : 'league',
          multiTeam: sourceTeamId === null,
          publishAll: true,
        })},now()
      )
      ON CONFLICT(id) DO UPDATE SET
        name=excluded.name,source_type=excluded.source_type,team_id=excluded.team_id,
        league_wide=excluded.league_wide,url=excluded.url,priority=excluded.priority,
        reliability_score=excluded.reliability_score,
        check_interval_seconds=excluded.check_interval_seconds,enabled=true,
        metadata=excluded.metadata,
        next_check_at=CASE WHEN ${force} THEN now() ELSE content_sources.next_check_at END,
        updated_at=now()
    `;
  }
  return sources.length;
}
