export const GAME_DAY_HERO_ASSETS: Record<string, string> = {
  ARI: '/images/gameday/stadium/az/gameday.png',
  ATL: '/images/gameday/stadium/atl/gameday.png',
  BAL: '/images/gameday/stadium/bal/gameday.png',
  BUF: '/images/gameday/stadium/buf/gameday.png',
  CAR: '/images/gameday/stadium/car/gameday.png',
  CHI: '/images/gameday/stadium/chi/gameday.png',
  CIN: '/images/gameday/stadium/cin/gameday.png',
  CLE: '/images/gameday/stadium/cle/gameday.png',
  DAL: '/images/gameday/stadium/dal/gameday.png',
  DEN: '/images/gameday/stadium/den/gameday.png',
  DET: '/images/gameday/stadium/det/gameday.png',
  GB: '/images/gameday/stadium/gb/gameday.png',
  HOU: '/images/gameday/stadium/hou/gameday.png',
  IND: '/images/gameday/stadium/ind/gameday.png',
  JAX: '/images/gameday/stadium/jax/gameday.png',
  KC: '/images/gameday/stadium/kc/gameday.png',
  LAC: '/images/gameday/stadium/lac/gameday.png',
  LAR: '/images/gameday/stadium/lar/gameday.png',
  LV: '/images/gameday/stadium/lv/gameday.png',
  MIA: '/images/gameday/stadium/mia/gameday.png',
  MIN: '/images/gameday/stadium/min/gameday.png',
  NE: '/images/gameday/stadium/ne/gameday.png',
  NO: '/images/gameday/stadium/no/gameday.png',
  NYG: '/images/gameday/stadium/nyg/gameday.png',
  NYJ: '/images/gameday/stadium/nyj/gameday.png',
  PHI: '/images/gameday/stadium/phi/gameday.png',
  PIT: '/images/gameday/stadium/pit/gameday.png',
  SEA: '/images/gameday/stadium/sea/gameday.png',
  SF: '/images/gameday/stadium/san/gameday.png',
  TB: '/images/gameday/stadium/tb/gameday.png',
  TEN: '/images/gameday/stadium/ten/gameday.png',
  WAS: '/images/gameday/stadium/was/gameday.png',
};

export const TEAM_TIME_ZONES: Record<string, string> = {
  ARI: 'America/Phoenix',
  ATL: 'America/New_York',
  BAL: 'America/New_York',
  BUF: 'America/New_York',
  CAR: 'America/New_York',
  CHI: 'America/Chicago',
  CIN: 'America/New_York',
  CLE: 'America/New_York',
  DAL: 'America/Chicago',
  DEN: 'America/Denver',
  DET: 'America/Detroit',
  GB: 'America/Chicago',
  HOU: 'America/Chicago',
  IND: 'America/Indiana/Indianapolis',
  JAX: 'America/New_York',
  KC: 'America/Chicago',
  LAC: 'America/Los_Angeles',
  LAR: 'America/Los_Angeles',
  LV: 'America/Los_Angeles',
  MIA: 'America/New_York',
  MIN: 'America/Chicago',
  NE: 'America/New_York',
  NO: 'America/Chicago',
  NYG: 'America/New_York',
  NYJ: 'America/New_York',
  PHI: 'America/New_York',
  PIT: 'America/New_York',
  SEA: 'America/Los_Angeles',
  SF: 'America/Los_Angeles',
  TB: 'America/New_York',
  TEN: 'America/Chicago',
  WAS: 'America/New_York',
};

export const gameDayHeroAsset = (teamAbbr: string) => GAME_DAY_HERO_ASSETS[teamAbbr];

export const teamTimeZone = (teamAbbr: string) => TEAM_TIME_ZONES[teamAbbr] ?? 'America/New_York';
