"""Generate static native require mappings. Never modifies supplied PNG files."""
from pathlib import Path
import struct
import shutil
root=Path('public/assets/huddle-field-assets')
base=root/'base_field.png'
def size(path):
    return struct.unpack('>II',path.read_bytes()[16:24])
assert size(base)==(1614,304)
overlay_root=Path('public/assets/huddle-field-aligned')
files=sorted((overlay_root/'endzones').glob('*/*.png'))
assert len(files)==64
assert all(size(p)==size(base) for p in files)
native_root=Path('apps/mobile/assets/huddle-field')
native_root.mkdir(parents=True,exist_ok=True)
shutil.copyfile(base,native_root/'base_field.png')
shutil.copytree(overlay_root/'endzones',native_root/'endzones',dirs_exist_ok=True)
rows=[]
for folder in sorted((overlay_root/'endzones').iterdir()):
    if folder.is_dir():
        rows.append(f"  {folder.name}: {{ left: require('../assets/huddle-field/endzones/{folder.name}/left.png'), right: require('../assets/huddle-field/endzones/{folder.name}/right.png') }},")
Path('apps/mobile/lib/huddle-field-assets.ts').write_text("// Generated by scripts/build-huddle-field-assets.py. Exact supplied PNG assets.\nexport const nativeFieldBase = require('../assets/huddle-field/base_field.png');\nexport const nativeEndZones: Record<string, {left:number;right:number}> = {\n"+'\n'.join(rows)+"\n};\n")
print('Verified base + 64 overlays share 1614×304 bounds; native mapping generated.')
