"""Generate React icons from the supplied SVG collection. Run from repository root."""
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
root = Path('public/assets/down-distance-football-icons')
manifest = json.loads((root / 'manifest.json').read_text())
lines = ["'use client';", "", "// Generated by scripts/generate-football-icons.py. Edit the source SVGs, then regenerate.", "import { forwardRef, type ReactNode } from 'react';", "import type { LucideProps } from 'lucide-react';", "", "function createIcon(name: string, geometry: ReactNode) {", "  const Icon = forwardRef<SVGSVGElement, LucideProps & { title?: string }>(", "    ({ size = 24, strokeWidth = 2, absoluteStrokeWidth, title, children, ...props }, ref) => (", '      <svg ref={ref} xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={absoluteStrokeWidth ? Number(strokeWidth) * 24 / Number(size) : strokeWidth} strokeLinecap="round" strokeLinejoin="round" focusable="false" aria-hidden={title || props["aria-label"] || props["aria-labelledby"] ? undefined : true} role={title ? "img" : undefined} {...props}>', '        {title && <title>{title}</title>}{geometry}{children}', '      </svg>', '    ),', '  );', '  Icon.displayName = name;', '  return Icon;', '}', '']
def node(el):
 tag=el.tag.split('}')[-1]
 attrs=[]
 for k,v in el.attrib.items():
  k=re.sub(r'-([a-z])',lambda m:m[1].upper(),k)
  attrs.append(f'{k}={{{json.dumps(v)}}}')
 return '<'+tag+(' '+' '.join(attrs) if attrs else '')+' />'
for item in manifest['icons']:
 svg=ET.fromstring((root/item['path']).read_text())
 name='Dd'+''.join(part.title() for part in Path(item['path']).stem.split('-'))+'Icon'
 geometry=''.join(node(el) for el in svg if el.tag.split('}')[-1]!='title')
 lines.extend([f'/** {item["path"]} */',f'export const {name} = /*#__PURE__*/ createIcon("{name}", <>{geometry}</>);',''])
Path('src/components/ui/football-icons.tsx').write_text('\n'.join(lines))
