"""Generate theme-aware React icons from the supplied Ownership manifest."""
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'public/assets/down-and-distance-ownership-icons'
manifest = json.loads((SOURCE / 'manifest.json').read_text())
ATTRS = {'stroke-width': 'strokeWidth', 'stroke-linecap': 'strokeLinecap', 'stroke-linejoin': 'strokeLinejoin', 'fill-rule': 'fillRule', 'clip-rule': 'clipRule'}

def node(element):
    tag = element.tag.split('}')[-1]
    assert tag in {'path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon', 'g'}, tag
    attrs = ' '.join(f'{ATTRS.get(k,k)}={{{json.dumps(v)}}}' for k,v in element.attrib.items())
    children = ''.join(node(child) for child in element)
    return f'<{tag} {attrs}>{children}</{tag}>' if children else f'<{tag} {attrs} />'

entries = []
for icon in manifest['icons']:
    svg = ET.parse(SOURCE / icon['path']).getroot()
    for key, value in {'viewBox':'0 0 24 24','fill':'none','stroke':'currentColor','stroke-width':'1.75','stroke-linecap':'round','stroke-linejoin':'round'}.items():
        assert svg.get(key) == value, (icon['name'], key)
    entries.append(f"  {json.dumps(icon['name'])}: <>{''.join(node(child) for child in svg)}</>,")
assert len(entries) == manifest['count']
output = ''''use client';

// Generated by scripts/generate-ownership-icons.py from the supplied manifest and SVGs.
import React, { forwardRef, type SVGProps } from 'react';

const geometry = {
'''+ '\n'.join(entries)+'''
} as const;

export type OwnershipIconName = keyof typeof geometry;
export type OwnershipIconProps = Omit<SVGProps<SVGSVGElement>, 'name' | 'width' | 'height' | 'viewBox' | 'fill' | 'stroke' | 'strokeWidth' | 'strokeLinecap' | 'strokeLinejoin' | 'children'> & {
  name: OwnershipIconName;
  size?: number | string;
  title?: string;
};
export const OwnershipIcon = forwardRef<SVGSVGElement, OwnershipIconProps>(
  ({ name, size = 24, title, ...props }, ref) => {
    const labeled = Boolean(title || props['aria-label'] || props['aria-labelledby']);
    return <svg {...props} data-ownership-icon={name} ref={ref} xmlns="http://www.w3.org/2000/svg" width={size} height={size}
      viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.75}
      strokeLinecap="round" strokeLinejoin="round" focusable="false"
      aria-hidden={props['aria-hidden'] ?? (labeled ? undefined : true)}
      role={props.role ?? (labeled ? 'img' : undefined)}>
      {title && <title>{title}</title>}
      {geometry[name]}
    </svg>;
  }
);
OwnershipIcon.displayName = 'OwnershipIcon';
'''
(ROOT / 'src/components/ui/ownership-icon.tsx').write_text(output)
