'use client';

// Generated by scripts/generate-football-icons.py. Edit the source SVGs, then regenerate.
import { forwardRef, type ReactNode } from 'react';
import type { LucideProps } from 'lucide-react';

function createIcon(name: string, geometry: ReactNode) {
  const Icon = forwardRef<SVGSVGElement, LucideProps & { title?: string }>(
    ({ size = 24, strokeWidth = 2, absoluteStrokeWidth, title, children, ...props }, ref) => (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={absoluteStrokeWidth ? (Number(strokeWidth) * 24) / Number(size) : strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
        focusable="false"
        aria-hidden={title || props['aria-label'] || props['aria-labelledby'] ? undefined : true}
        role={title ? 'img' : undefined}
        {...props}
      >
        {title && <title>{title}</title>}
        {geometry}
        {children}
      </svg>
    ),
  );
  Icon.displayName = name;
  return Icon;
}

/** draft/draft-central.svg */
export const DdDraftCentralIcon = /*#__PURE__*/ createIcon(
  'DdDraftCentralIcon',
  <>
    <rect x={'4'} y={'11'} width={'16'} height={'10'} rx={'2'} />
    <path d={'M8 11V7C8 1 16 1 16 7V11'} />
  </>,
);

/** draft/mock-draft.svg */
export const DdMockDraftIcon = /*#__PURE__*/ createIcon(
  'DdMockDraftIcon',
  <>
    <path d={'M3 3V21H21 M7 16V12 M12 16V7 M17 16V10'} />
  </>,
);

/** draft/big-board.svg */
export const DdBigBoardIcon = /*#__PURE__*/ createIcon(
  'DdBigBoardIcon',
  <>
    <rect x={'4'} y={'5'} width={'16'} height={'17'} rx={'2'} />
    <rect x={'8'} y={'2'} width={'8'} height={'5'} rx={'2'} />
    <path d={'M8 11H9 M13 11H16'} />
    <path d={'M8 16H9 M13 16H16'} />
  </>,
);

/** draft/draft-guide.svg */
export const DdDraftGuideIcon = /*#__PURE__*/ createIcon(
  'DdDraftGuideIcon',
  <>
    <rect x={'7'} y={'3'} width={'14'} height={'17'} rx={'2'} />
    <path d={'M7 8H3V21H17 M11 7H17 M11 11H17 M11 15H15'} />
  </>,
);

/** draft/prospects.svg */
export const DdProspectsIcon = /*#__PURE__*/ createIcon(
  'DdProspectsIcon',
  <>
    <circle cx={'9'} cy={'7'} r={'3'} />
    <path d={'M3 20V17Q3 12 9 12H11 M17 11L19 15L22 16L19 18L18 22L16 19L12 18L15 15Z'} />
  </>,
);

/** draft/combine.svg */
export const DdCombineIcon = /*#__PURE__*/ createIcon(
  'DdCombineIcon',
  <>
    <circle cx={'12'} cy={'13'} r={'8'} />
    <path d={'M12 9V13L16 15 M9 2H15 M12 2V5'} />
    <path d={'M17 5L19 3'} />
  </>,
);

/** draft/draft-classes.svg */
export const DdDraftClassesIcon = /*#__PURE__*/ createIcon(
  'DdDraftClassesIcon',
  <>
    <path d={'M3 7L12 3L21 7L12 11Z M3 12L12 16L21 12 M3 17L12 21L21 17'} />
  </>,
);

/** draft/my-drafts.svg */
export const DdMyDraftsIcon = /*#__PURE__*/ createIcon(
  'DdMyDraftsIcon',
  <>
    <path
      d={'M7 3H17V10C17 17 7 17 7 10Z M7 5H3V8Q3 12 7 12 M17 5H21V8Q21 12 17 12 M12 15V20 M8 21H16'}
    />
  </>,
);

/** draft/trade-machine.svg */
export const DdTradeMachineIcon = /*#__PURE__*/ createIcon(
  'DdTradeMachineIcon',
  <>
    <path d={'M4 7H20L16 3'} />
    <path d={'M20 17H4L8 21'} />
  </>,
);

/** roster-team-management/roster.svg */
export const DdRosterIcon = /*#__PURE__*/ createIcon(
  'DdRosterIcon',
  <>
    <circle cx={'9'} cy={'7'} r={'3'} />
    <path d={'M3 21V18Q3 12 9 12Q15 12 15 18V21 M17 5Q22 7 17 10 M18 13Q22 14 22 19'} />
  </>,
);

/** roster-team-management/depth-chart.svg */
export const DdDepthChartIcon = /*#__PURE__*/ createIcon(
  'DdDepthChartIcon',
  <>
    <rect x={'9'} y={'2'} width={'6'} height={'5'} rx={'1'} />
    <rect x={'2'} y={'17'} width={'6'} height={'5'} rx={'1'} />
    <rect x={'16'} y={'17'} width={'6'} height={'5'} rx={'1'} />
    <path d={'M12 7V12 M5 17V12H19V17'} />
  </>,
);

/** roster-team-management/contracts.svg */
export const DdContractsIcon = /*#__PURE__*/ createIcon(
  'DdContractsIcon',
  <>
    <path d={'M14 3H6Q4 3 4 5V19Q4 21 6 21H18Q20 21 20 19V9Z M14 3V9H20'} />
    <path d={'M8 13H15 M8 17H12 M14 18L17 15'} />
  </>,
);

/** roster-team-management/free-agency.svg */
export const DdFreeAgencyIcon = /*#__PURE__*/ createIcon(
  'DdFreeAgencyIcon',
  <>
    <circle cx={'12'} cy={'6'} r={'3'} />
    <path d={'M5 21V18C5 11 19 11 19 18V21'} />
    <path d={'M18 9H22 M20 7V11'} />
  </>,
);

/** roster-team-management/trade-hub.svg */
export const DdTradeHubIcon = /*#__PURE__*/ createIcon(
  'DdTradeHubIcon',
  <>
    <circle cx={'5'} cy={'5'} r={'2'} />
    <circle cx={'19'} cy={'19'} r={'2'} />
    <path d={'M9 5H19V12 M16 9L19 12L22 9 M15 19H5V12 M2 15L5 12L8 15'} />
  </>,
);

/** roster-team-management/practice-squad.svg */
export const DdPracticeSquadIcon = /*#__PURE__*/ createIcon(
  'DdPracticeSquadIcon',
  <>
    <path d={'M5 17L10 3H14L19 17 M7 11H17 M3 21H21 M3 17H21'} />
  </>,
);

/** roster-team-management/cap-space.svg */
export const DdCapSpaceIcon = /*#__PURE__*/ createIcon(
  'DdCapSpaceIcon',
  <>
    <path d={'M3 18V11C3 1 21 1 21 11V18 M3 18H21 M7 18V15 M12 18V13 M17 18V10'} />
  </>,
);

/** roster-team-management/settings.svg */
export const DdSettingsIcon = /*#__PURE__*/ createIcon(
  'DdSettingsIcon',
  <>
    <path d={'M4 6H20 M4 12H20 M4 18H20'} />
    <rect x={'7'} y={'4'} width={'4'} height={'4'} rx={'1'} />
    <rect x={'14'} y={'10'} width={'4'} height={'4'} rx={'1'} />
    <rect x={'6'} y={'16'} width={'4'} height={'4'} rx={'1'} />
  </>,
);

/** roster-team-management/staff.svg */
export const DdStaffIcon = /*#__PURE__*/ createIcon(
  'DdStaffIcon',
  <>
    <circle cx={'12'} cy={'7'} r={'3'} />
    <path d={'M4 21V18Q4 12 12 12Q20 12 20 18V21 M10 13L12 16L14 13 M12 16V20'} />
  </>,
);

/** players-positions/quarterback.svg */
export const DdQuarterbackIcon = /*#__PURE__*/ createIcon(
  'DdQuarterbackIcon',
  <>
    <circle cx={'9'} cy={'5'} r={'2'} />
    <path d={'M8 9L12 12L17 8 M8 9L5 14 M10 11L10 16L6 21 M10 16L16 20'} />
    <path d={'M17 3Q21 2 22 6Q18 7 17 3Z'} />
  </>,
);

/** players-positions/running-back.svg */
export const DdRunningBackIcon = /*#__PURE__*/ createIcon(
  'DdRunningBackIcon',
  <>
    <circle cx={'14'} cy={'4'} r={'2'} />
    <path d={'M12 8L9 13L15 15L18 20 M9 13L6 19H3 M12 8L6 9L3 12 M13 10L17 12'} />
    <path d={'M17 8Q22 8 21 13Q16 13 17 8Z'} />
  </>,
);

/** players-positions/wide-receiver.svg */
export const DdWideReceiverIcon = /*#__PURE__*/ createIcon(
  'DdWideReceiverIcon',
  <>
    <circle cx={'12'} cy={'9'} r={'2'} />
    <path
      d={'M8 4L8 12L12 14L16 12V4 M12 14V17 M12 17L7 22 M12 17L17 22 M10 2Q12 0 14 2Q12 5 10 2Z'}
    />
  </>,
);

/** players-positions/tight-end.svg */
export const DdTightEndIcon = /*#__PURE__*/ createIcon(
  'DdTightEndIcon',
  <>
    <circle cx={'8'} cy={'5'} r={'2'} />
    <path d={'M3 12L6 9H12L15 12 M8 10V16L4 21 M8 16L12 21 M17 20V10Q17 7 21 7 M18 4L21 7L18 10'} />
  </>,
);

/** players-positions/offensive-line.svg */
export const DdOffensiveLineIcon = /*#__PURE__*/ createIcon(
  'DdOffensiveLineIcon',
  <>
    <circle cx={'5'} cy={'7'} r={'2'} />
    <circle cx={'12'} cy={'7'} r={'2'} />
    <circle cx={'19'} cy={'7'} r={'2'} />
    <path d={'M2 17V14Q5 10 8 14V17 M9 17V14Q12 10 15 14V17 M16 17V14Q19 10 22 14V17 M3 21H21'} />
  </>,
);

/** players-positions/defensive-line.svg */
export const DdDefensiveLineIcon = /*#__PURE__*/ createIcon(
  'DdDefensiveLineIcon',
  <>
    <path
      d={
        'M3 4H21 M3 9L7 13 M7 9L3 13 M10 9L14 13 M14 9L10 13 M17 9L21 13 M21 9L17 13 M5 21V17 M12 21V17 M19 21V17'
      }
    />
  </>,
);

/** players-positions/edge-rusher.svg */
export const DdEdgeRusherIcon = /*#__PURE__*/ createIcon(
  'DdEdgeRusherIcon',
  <>
    <path d={'M3 20V10Q3 4 9 4H18 M14 1L18 4L14 7 M9 12L13 16 M13 12L9 16 M18 14V21 M15 18H21'} />
  </>,
);

/** players-positions/linebacker.svg */
export const DdLinebackerIcon = /*#__PURE__*/ createIcon(
  'DdLinebackerIcon',
  <>
    <path d={'M12 3C9 5 6 6 4 6V12C4 17 8 20 12 22C16 20 20 17 20 12V6C18 6 15 5 12 3Z'} />
    <path d={'M8 10L12 14L16 10 M12 14V18'} />
  </>,
);

/** players-positions/cornerback.svg */
export const DdCornerbackIcon = /*#__PURE__*/ createIcon(
  'DdCornerbackIcon',
  <>
    <path d={'M4 3V20H21 M8 6L12 10 M12 6L8 10 M10 13V16H18 M15 13L18 16L15 19'} />
  </>,
);

/** players-positions/safety.svg */
export const DdSafetyIcon = /*#__PURE__*/ createIcon(
  'DdSafetyIcon',
  <>
    <path d={'M3 19C3 9 21 9 21 19 M3 5H21'} />
    <circle cx={'12'} cy={'7'} r={'2'} />
    <path d={'M12 12V18 M9 16L12 19L15 16'} />
  </>,
);

/** players-positions/kicker.svg */
export const DdKickerIcon = /*#__PURE__*/ createIcon(
  'DdKickerIcon',
  <>
    <circle cx={'10'} cy={'4'} r={'2'} />
    <path d={'M10 8L8 13L5 20 M8 13L14 16L19 12 M9 9L4 11 M11 9L15 11 M17 21H22 M20 18V21'} />
  </>,
);

/** players-positions/punter.svg */
export const DdPunterIcon = /*#__PURE__*/ createIcon(
  'DdPunterIcon',
  <>
    <circle cx={'9'} cy={'4'} r={'2'} />
    <path d={'M9 8L7 13L4 21 M7 13L13 17L18 12 M9 9L14 10 M13 4Q18 3 19 7Q14 8 13 4Z M21 10V14'} />
  </>,
);

/** news/all-news.svg */
export const DdAllNewsIcon = /*#__PURE__*/ createIcon(
  'DdAllNewsIcon',
  <>
    <rect x={'3'} y={'4'} width={'15'} height={'17'} rx={'2'} />
    <path d={'M18 9H22V19Q22 21 20 21H17 M7 8H14 M7 12H10 M7 16H14'} />
  </>,
);

/** news/rumors.svg */
export const DdRumorsIcon = /*#__PURE__*/ createIcon(
  'DdRumorsIcon',
  <>
    <path
      d={
        'M4 4H20Q22 4 22 6V14Q22 16 20 16H10L4 21V16Q2 16 2 14V6Q2 4 4 4Z M7 10H8 M12 10H13 M17 10H18'
      }
    />
  </>,
);

/** news/injuries.svg */
export const DdInjuriesIcon = /*#__PURE__*/ createIcon(
  'DdInjuriesIcon',
  <>
    <rect x={'3'} y={'3'} width={'18'} height={'18'} rx={'4'} />
    <path d={'M12 7V17 M7 12H17'} />
  </>,
);

/** news/transactions.svg */
export const DdTransactionsIcon = /*#__PURE__*/ createIcon(
  'DdTransactionsIcon',
  <>
    <path d={'M4 4H15L11 1 M15 20H4L8 23 M4 8V16 M20 6V18 M17 9L20 6L23 9'} />
  </>,
);

/** news/contracts-news.svg */
export const DdContractsNewsIcon = /*#__PURE__*/ createIcon(
  'DdContractsNewsIcon',
  <>
    <path d={'M11 21H4V3H14L20 9V11 M14 3V9H20 M8 12H11 M8 16H10'} />
    <circle cx={'18'} cy={'18'} r={'4'} />
    <path d={'M18 16V20 M16 18H20'} />
  </>,
);

/** news/game-recaps.svg */
export const DdGameRecapsIcon = /*#__PURE__*/ createIcon(
  'DdGameRecapsIcon',
  <>
    <rect x={'3'} y={'3'} width={'18'} height={'18'} rx={'2'} />
    <path d={'M9 8L16 12L9 16Z'} />
  </>,
);

/** news/analysis.svg */
export const DdAnalysisIcon = /*#__PURE__*/ createIcon(
  'DdAnalysisIcon',
  <>
    <path d={'M14 3H6Q4 3 4 5V19Q4 21 6 21H18Q20 21 20 19V9Z M14 3V9H20'} />
    <path d={'M8 17V14 M12 17V11 M16 17V13'} />
  </>,
);

/** news/my-team.svg */
export const DdMyTeamIcon = /*#__PURE__*/ createIcon(
  'DdMyTeamIcon',
  <>
    <path d={'M12 3C9 5 6 6 4 6V12C4 17 8 20 12 22C16 20 20 17 20 12V6C18 6 15 5 12 3Z'} />
    <path d={'M8 12L11 15L16 9'} />
  </>,
);

/** game-season/schedule.svg */
export const DdScheduleIcon = /*#__PURE__*/ createIcon(
  'DdScheduleIcon',
  <>
    <rect x={'3'} y={'5'} width={'18'} height={'17'} rx={'2'} />
    <path d={'M7 2V7 M17 2V7 M3 10H21 M7 14H9 M15 14H17 M7 18H9'} />
  </>,
);

/** game-season/standings.svg */
export const DdStandingsIcon = /*#__PURE__*/ createIcon(
  'DdStandingsIcon',
  <>
    <path d={'M3 21V13H9V21 M9 21V5H15V21 M15 21V10H21V21 M2 21H22 M11 2H13'} />
  </>,
);

/** game-season/playoffs.svg */
export const DdPlayoffsIcon = /*#__PURE__*/ createIcon(
  'DdPlayoffsIcon',
  <>
    <path d={'M3 3V9H8V15H3V21 M21 3V9H16V15H21V21 M8 12H16'} />
    <circle cx={'12'} cy={'12'} r={'2'} />
  </>,
);

/** game-season/stadiums.svg */
export const DdStadiumsIcon = /*#__PURE__*/ createIcon(
  'DdStadiumsIcon',
  <>
    <path
      d={
        'M3 9Q12 3 21 9V18Q12 23 3 18Z M3 9Q12 15 21 9 M3 15Q12 20 21 15 M6 6V3 M18 6V3 M8 13V17 M16 13V17'
      }
    />
  </>,
);

/** game-season/tickets.svg */
export const DdTicketsIcon = /*#__PURE__*/ createIcon(
  'DdTicketsIcon',
  <>
    <path d={'M3 6H21V10C17 10 17 14 21 14V18H3V14C7 14 7 10 3 10Z M15 6V8 M15 11V13 M15 16V18'} />
  </>,
);

/** game-season/scores.svg */
export const DdScoresIcon = /*#__PURE__*/ createIcon(
  'DdScoresIcon',
  <>
    <rect x={'2'} y={'5'} width={'20'} height={'15'} rx={'2'} />
    <path d={'M8 2V5 M16 2V5 M12 9V17 M6 10H8V15H6 M16 10H18V15H16'} />
  </>,
);

/** game-season/game-center.svg */
export const DdGameCenterIcon = /*#__PURE__*/ createIcon(
  'DdGameCenterIcon',
  <>
    <rect x={'2'} y={'3'} width={'20'} height={'15'} rx={'2'} />
    <path d={'M8 22H16 M12 18V22 M10 7L16 10.5L10 14Z'} />
  </>,
);

/** game-season/rivalries.svg */
export const DdRivalriesIcon = /*#__PURE__*/ createIcon(
  'DdRivalriesIcon',
  <>
    <path
      d={
        'M3 3L10 10 M3 3L3 7 M3 3H7 M21 3L14 10 M21 3H17 M21 3V7 M3 21L9 15 M21 21L15 15 M6 12L12 18L18 12 M7 17L10 20 M14 20L17 17'
      }
    />
  </>,
);

/** game-season/league-leaders.svg */
export const DdLeagueLeadersIcon = /*#__PURE__*/ createIcon(
  'DdLeagueLeadersIcon',
  <>
    <path d={'M3 8L7 12L12 4L17 12L21 8L19 19H5Z M6 22H18'} />
  </>,
);

/** game-season/awards.svg */
export const DdAwardsIcon = /*#__PURE__*/ createIcon(
  'DdAwardsIcon',
  <>
    <circle cx={'12'} cy={'9'} r={'6'} />
    <path d={'M7 14L5 22L12 18L19 22L17 14 M10 9L12 11L15 7'} />
  </>,
);

/** media-content/videos.svg */
export const DdVideosIcon = /*#__PURE__*/ createIcon(
  'DdVideosIcon',
  <>
    <rect x={'2'} y={'5'} width={'14'} height={'15'} rx={'2'} />
    <path d={'M16 10L22 7V18L16 15 M6 9L12 12.5L6 16Z'} />
  </>,
);

/** media-content/highlights.svg */
export const DdHighlightsIcon = /*#__PURE__*/ createIcon(
  'DdHighlightsIcon',
  <>
    <path d={'M13 2L4 14H11L10 22L20 9H13Z'} />
  </>,
);

/** media-content/podcasts.svg */
export const DdPodcastsIcon = /*#__PURE__*/ createIcon(
  'DdPodcastsIcon',
  <>
    <rect x={'9'} y={'2'} width={'6'} height={'13'} rx={'3'} />
    <path d={'M5 10V12C5 21 19 21 19 12V10 M12 19V22 M8 22H16'} />
  </>,
);

/** media-content/articles.svg */
export const DdArticlesIcon = /*#__PURE__*/ createIcon(
  'DdArticlesIcon',
  <>
    <path d={'M14 3H6Q4 3 4 5V19Q4 21 6 21H18Q20 21 20 19V9Z M14 3V9H20'} />
    <path d={'M8 12H16 M8 16H16 M8 19H12'} />
  </>,
);

/** media-content/photo-gallery.svg */
export const DdPhotoGalleryIcon = /*#__PURE__*/ createIcon(
  'DdPhotoGalleryIcon',
  <>
    <rect x={'5'} y={'2'} width={'17'} height={'17'} rx={'2'} />
    <path d={'M2 7V22H17 M5 15L10 10L15 15L18 12L22 16'} />
    <circle cx={'17'} cy={'7'} r={'1.5'} />
  </>,
);

/** media-content/live.svg */
export const DdLiveIcon = /*#__PURE__*/ createIcon(
  'DdLiveIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'2'} />
    <path
      d={
        'M7 7C4 10 4 14 7 17 M17 7C20 10 20 14 17 17 M3 3C0.8 8 0.8 16 3 21 M21 3C23.2 8 23.2 16 21 21'
      }
    />
  </>,
);

/** media-content/shows.svg */
export const DdShowsIcon = /*#__PURE__*/ createIcon(
  'DdShowsIcon',
  <>
    <rect x={'3'} y={'7'} width={'18'} height={'14'} rx={'2'} />
    <path d={'M7 2L12 7L17 2 M8 11L15 14L8 17Z'} />
  </>,
);

/** media-content/featured.svg */
export const DdFeaturedIcon = /*#__PURE__*/ createIcon(
  'DdFeaturedIcon',
  <>
    <path d={'M12 3L14.7 8.6L21 9.5L16.5 14L17.5 20.5L12 17.5L6.5 20.5L7.5 14L3 9.5L9.3 8.6Z'} />
    <circle cx={'12'} cy={'12'} r={'2'} />
  </>,
);

/** analysis-tools/stats.svg */
export const DdStatsIcon = /*#__PURE__*/ createIcon(
  'DdStatsIcon',
  <>
    <path d={'M3 21V14H7V21 M10 21V8H14V21 M17 21V3H21V21 M2 21H22'} />
  </>,
);

/** analysis-tools/trends.svg */
export const DdTrendsIcon = /*#__PURE__*/ createIcon(
  'DdTrendsIcon',
  <>
    <path d={'M3 19L9 12L13 15L21 5 M15 5H21V11'} />
  </>,
);

/** analysis-tools/team-analytics.svg */
export const DdTeamAnalyticsIcon = /*#__PURE__*/ createIcon(
  'DdTeamAnalyticsIcon',
  <>
    <circle cx={'7'} cy={'6'} r={'2'} />
    <circle cx={'17'} cy={'6'} r={'2'} />
    <path
      d={'M2 13Q2 10 7 10Q12 10 12 13 M13 11Q19 8 22 13 M4 21V17 M10 21V15 M16 21V18 M22 21V16'}
    />
  </>,
);

/** analysis-tools/player-comparison.svg */
export const DdPlayerComparisonIcon = /*#__PURE__*/ createIcon(
  'DdPlayerComparisonIcon',
  <>
    <circle cx={'5'} cy={'6'} r={'2'} />
    <circle cx={'19'} cy={'6'} r={'2'} />
    <path d={'M2 15V13Q5 9 8 13V15 M16 15V13Q19 9 22 13V15 M12 3V21 M3 19H8 M16 19H21'} />
  </>,
);

/** analysis-tools/filters.svg */
export const DdFiltersIcon = /*#__PURE__*/ createIcon(
  'DdFiltersIcon',
  <>
    <path d={'M3 4H21L14 12V20L10 22V12Z'} />
  </>,
);

/** analysis-tools/scouting.svg */
export const DdScoutingIcon = /*#__PURE__*/ createIcon(
  'DdScoutingIcon',
  <>
    <circle cx={'10'} cy={'10'} r={'6.5'} />
    <path d={'M15 15L21 21'} />
    <path d={'M7 10L9 12L13 8'} />
  </>,
);

/** analysis-tools/cap-space-tool.svg */
export const DdCapSpaceToolIcon = /*#__PURE__*/ createIcon(
  'DdCapSpaceToolIcon',
  <>
    <rect x={'3'} y={'3'} width={'18'} height={'18'} rx={'2'} />
    <path d={'M7 7H17 M7 12H9 M15 11V15 M13 13H17 M7 17H9'} />
  </>,
);

/** analysis-tools/trade-finder.svg */
export const DdTradeFinderIcon = /*#__PURE__*/ createIcon(
  'DdTradeFinderIcon',
  <>
    <circle cx={'9'} cy={'9'} r={'6'} />
    <path d={'M14 14L21 21 M5 8H12L10 6 M12 11H5L7 13'} />
  </>,
);

/** analysis-tools/data.svg */
export const DdDataIcon = /*#__PURE__*/ createIcon(
  'DdDataIcon',
  <>
    <path
      d={'M3 6C3 1 21 1 21 6C21 11 3 11 3 6Z M3 6V18C3 23 21 23 21 18V6 M3 12C3 17 21 17 21 12'}
    />
  </>,
);

/** analysis-tools/projections.svg */
export const DdProjectionsIcon = /*#__PURE__*/ createIcon(
  'DdProjectionsIcon',
  <>
    <path d={'M3 3V21H21 M6 17L10 13L13 15 M13 15L15 11 M17 8L20 4 M16 4H20V8'} />
  </>,
);

/** football-concepts/football.svg */
export const DdFootballIcon = /*#__PURE__*/ createIcon(
  'DdFootballIcon',
  <>
    <path d={'M4 20C2 11 11 2 20 4C22 13 13 22 4 20Z M8 16L16 8 M8 12L12 16 M12 8L16 12'} />
  </>,
);

/** football-concepts/playbook.svg */
export const DdPlaybookIcon = /*#__PURE__*/ createIcon(
  'DdPlaybookIcon',
  <>
    <path d={'M12 6C9 3 5 3 3 4V19C6 18 9 18 12 21C15 18 18 18 21 19V4C18 3 15 3 12 6Z M12 6V21'} />
    <path d={'M6 9L9 12 M9 9L6 12 M16 15V9H19'} />
  </>,
);

/** football-concepts/coach.svg */
export const DdCoachIcon = /*#__PURE__*/ createIcon(
  'DdCoachIcon',
  <>
    <path
      d={
        'M5 9V6Q5 2 12 2Q18 2 18 7 M5 7H21 M7 9V11C7 18 17 18 17 11V9 M3 22V20Q3 17 8 17 M16 17Q21 17 21 20V22'
      }
    />
  </>,
);

/** football-concepts/coordinator.svg */
export const DdCoordinatorIcon = /*#__PURE__*/ createIcon(
  'DdCoordinatorIcon',
  <>
    <path
      d={
        'M4 13V10C4 0 20 0 20 10V13 M4 10H7V16H4Z M17 10H20V16H17Z M20 16V19H13 M8 10V12Q8 17 13 17'
      }
    />
    <circle cx={'12'} cy={'19'} r={'1'} />
  </>,
);

/** football-concepts/game-clock.svg */
export const DdGameClockIcon = /*#__PURE__*/ createIcon(
  'DdGameClockIcon',
  <>
    <circle cx={'12'} cy={'13'} r={'8'} />
    <path d={'M12 9V13L16 15 M9 2H15 M12 2V5'} />
    <path d={'M5 4L3 6'} />
  </>,
);

/** football-concepts/yard-marker.svg */
export const DdYardMarkerIcon = /*#__PURE__*/ createIcon(
  'DdYardMarkerIcon',
  <>
    <path d={'M7 8V22 M17 8V22 M4 22H20 M7 18H17'} />
    <circle cx={'7'} cy={'5'} r={'3'} />
    <circle cx={'17'} cy={'5'} r={'3'} />
  </>,
);

/** football-concepts/first-down.svg */
export const DdFirstDownIcon = /*#__PURE__*/ createIcon(
  'DdFirstDownIcon',
  <>
    <path d={'M3 4V21 M3 5H20L16 2 M20 5L16 8 M8 12H15 M12 12V19 M9 19H15'} />
  </>,
);

/** football-concepts/referee.svg */
export const DdRefereeIcon = /*#__PURE__*/ createIcon(
  'DdRefereeIcon',
  <>
    <circle cx={'12'} cy={'7'} r={'3'} />
    <path d={'M3 2V10L7 14V22 M21 2V10L17 14V22 M7 13H17 M10 14V22 M14 14V22'} />
  </>,
);

/** football-concepts/field.svg */
export const DdFieldIcon = /*#__PURE__*/ createIcon(
  'DdFieldIcon',
  <>
    <rect x={'2'} y={'4'} width={'20'} height={'16'} rx={'2'} />
    <path d={'M6 4V20 M18 4V20 M12 4V20 M9 8V10 M9 14V16 M15 8V10 M15 14V16'} />
  </>,
);

/** football-concepts/touchdown.svg */
export const DdTouchdownIcon = /*#__PURE__*/ createIcon(
  'DdTouchdownIcon',
  <>
    <path d={'M4 2V11H20V2 M12 11V22 M8 22H16 M8 3Q12 1 16 3Q12 7 8 3Z'} />
  </>,
);

/** actions/add.svg */
export const DdAddIcon = /*#__PURE__*/ createIcon(
  'DdAddIcon',
  <>
    <path d={'M12 4V20 M4 12H20'} />
  </>,
);

/** actions/edit.svg */
export const DdEditIcon = /*#__PURE__*/ createIcon(
  'DdEditIcon',
  <>
    <path d={'M4 16L16 4Q18 2 20 4Q22 6 20 8L8 20L3 21Z M14 6L18 10 M4 16L8 20'} />
  </>,
);

/** actions/delete.svg */
export const DdDeleteIcon = /*#__PURE__*/ createIcon(
  'DdDeleteIcon',
  <>
    <path d={'M3 6H21 M8 6V3H16V6 M5 6L6 21H18L19 6 M10 10V17 M14 10V17'} />
  </>,
);

/** actions/copy.svg */
export const DdCopyIcon = /*#__PURE__*/ createIcon(
  'DdCopyIcon',
  <>
    <rect x={'8'} y={'8'} width={'13'} height={'13'} rx={'2'} />
    <path d={'M16 8V3H3V16H8'} />
  </>,
);

/** actions/share.svg */
export const DdShareIcon = /*#__PURE__*/ createIcon(
  'DdShareIcon',
  <>
    <circle cx={'5'} cy={'12'} r={'3'} />
    <circle cx={'19'} cy={'5'} r={'3'} />
    <circle cx={'19'} cy={'19'} r={'3'} />
    <path d={'M8 10L16 6 M8 14L16 18'} />
  </>,
);

/** actions/view.svg */
export const DdViewIcon = /*#__PURE__*/ createIcon(
  'DdViewIcon',
  <>
    <path d={'M2 12C7 3 17 3 22 12C17 21 7 21 2 12Z'} />
    <circle cx={'12'} cy={'12'} r={'3'} />
  </>,
);

/** actions/download.svg */
export const DdDownloadIcon = /*#__PURE__*/ createIcon(
  'DdDownloadIcon',
  <>
    <path d={'M12 2V16 M7 11L12 16L17 11 M3 16V21H21V16'} />
  </>,
);

/** actions/print.svg */
export const DdPrintIcon = /*#__PURE__*/ createIcon(
  'DdPrintIcon',
  <>
    <path d={'M6 8V2H18V8 M6 18H3V8H21V18H18 M6 14H18V22H6Z M17 11H18'} />
  </>,
);

/** status-indicators/favorite.svg */
export const DdFavoriteIcon = /*#__PURE__*/ createIcon(
  'DdFavoriteIcon',
  <>
    <path d={'M12 3L14.7 8.6L21 9.5L16.5 14L17.5 20.5L12 17.5L6.5 20.5L7.5 14L3 9.5L9.3 8.6Z'} />
  </>,
);

/** status-indicators/save.svg */
export const DdSaveIcon = /*#__PURE__*/ createIcon(
  'DdSaveIcon',
  <>
    <path d={'M5 3H19V22L12 17L5 22Z'} />
  </>,
);

/** status-indicators/hide.svg */
export const DdHideIcon = /*#__PURE__*/ createIcon(
  'DdHideIcon',
  <>
    <path d={'M3 3L21 21 M8 6Q16 3 22 12Q20 15 18 16 M14 18Q7 20 2 12L5 8 M10 10Q8 15 14 14'} />
  </>,
);

/** status-indicators/active.svg */
export const DdActiveIcon = /*#__PURE__*/ createIcon(
  'DdActiveIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'9'} />
    <path d={'M7 12L11 16L17 8'} />
  </>,
);

/** status-indicators/pending.svg */
export const DdPendingIcon = /*#__PURE__*/ createIcon(
  'DdPendingIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'9'} />
    <path d={'M12 6V12L16 15'} />
  </>,
);

/** status-indicators/inactive.svg */
export const DdInactiveIcon = /*#__PURE__*/ createIcon(
  'DdInactiveIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'9'} />
    <path d={'M8 12H16'} />
  </>,
);

/** status-indicators/rising.svg */
export const DdRisingIcon = /*#__PURE__*/ createIcon(
  'DdRisingIcon',
  <>
    <path d={'M5 20V14H9V9H14V4H21 M17 1L21 4L17 7'} />
  </>,
);

/** status-indicators/falling.svg */
export const DdFallingIcon = /*#__PURE__*/ createIcon(
  'DdFallingIcon',
  <>
    <path d={'M5 4V10H9V15H14V20H21 M17 17L21 20L17 23'} />
  </>,
);

/** status-indicators/out.svg */
export const DdOutIcon = /*#__PURE__*/ createIcon(
  'DdOutIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'9'} />
    <path d={'M8 8L16 16 M16 8L8 16'} />
  </>,
);

/** ui-navigation/home.svg */
export const DdHomeIcon = /*#__PURE__*/ createIcon(
  'DdHomeIcon',
  <>
    <path d={'M2 11L12 3L22 11 M5 9V21H10V15H14V21H19V9'} />
  </>,
);

/** ui-navigation/menu.svg */
export const DdMenuIcon = /*#__PURE__*/ createIcon(
  'DdMenuIcon',
  <>
    <path d={'M3 5H21 M3 12H21 M3 19H21'} />
  </>,
);

/** ui-navigation/search.svg */
export const DdSearchIcon = /*#__PURE__*/ createIcon(
  'DdSearchIcon',
  <>
    <circle cx={'10'} cy={'10'} r={'6.5'} />
    <path d={'M15 15L21 21'} />
  </>,
);

/** ui-navigation/notifications.svg */
export const DdNotificationsIcon = /*#__PURE__*/ createIcon(
  'DdNotificationsIcon',
  <>
    <path d={'M4 18L6 14V9C6 1 18 1 18 9V14L20 18Z M9 21Q12 24 15 21 M12 2V3'} />
  </>,
);

/** ui-navigation/messages.svg */
export const DdMessagesIcon = /*#__PURE__*/ createIcon(
  'DdMessagesIcon',
  <>
    <path d={'M3 3H21V17H10L3 22Z M7 8H17 M7 12H14'} />
  </>,
);

/** ui-navigation/profile.svg */
export const DdProfileIcon = /*#__PURE__*/ createIcon(
  'DdProfileIcon',
  <>
    <circle cx={'12'} cy={'6'} r={'3'} />
    <path d={'M5 21V18C5 11 19 11 19 18V21'} />
  </>,
);

/** ui-navigation/info.svg */
export const DdInfoIcon = /*#__PURE__*/ createIcon(
  'DdInfoIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'9'} />
    <path d={'M12 7H12.01 M10 11H12V17 M10 17H14'} />
  </>,
);

/** ui-navigation/help.svg */
export const DdHelpIcon = /*#__PURE__*/ createIcon(
  'DdHelpIcon',
  <>
    <circle cx={'12'} cy={'12'} r={'9'} />
    <path d={'M9 8C9 4 17 5 15 10L12 13 M12 17H12.01'} />
  </>,
);

/** ui-navigation/more.svg */
export const DdMoreIcon = /*#__PURE__*/ createIcon(
  'DdMoreIcon',
  <>
    <circle cx={'4'} cy={'12'} r={'1'} />
    <circle cx={'12'} cy={'12'} r={'1'} />
    <circle cx={'20'} cy={'12'} r={'1'} />
  </>,
);
